FROM openjdk:8-jdk-alpine

ADD . /ConfigServer
WORKDIR /ConfigServer
ARG CALIBER_CONFIG_GIT_URI
ARG CALIBER_CONFIG_GIT_USERNAME
ARG CALIBER_CONFIG_GIT_PASSWORD
ENV CALIBER_CONFIG_GIT_URI $CALIBER_CONFIG_GIT_URI
ENV CALIBER_CONFIG_GIT_USERNAME $CALIBER_CONFIG_GIT_USERNAME
ENV CALIBER_CONFIG_GIT_PASSWORD $CALIBER_CONFIG_GIT_PASSWORD
EXPOSE 8888
ENTRYPOINT ["java", "-Dspring.profiles.active=qa", "-jar", "target/caliber-config-1.0.jar"]
